import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Slab } from 'next/font/google'
import Navbar from './components/Navbar'

const roboto = Roboto_Slab({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar username='waqas@email.com' />
        <main>
        {children}
        </main>
        </body>
    </html>

  )
}
