import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import Navbar from "./components/Navbar";
import AuthProvider from "./auth/Provider";

const roboto = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
         <Navbar />
        <main className="h-fit">{children}</main>
        </AuthProvider>    
           
        
      </body>
    </html>
  );
}
